// Metadata for all achievement types (spec-defined keys + DB enum aliases)
export const ACHIEVEMENT_META = {
  // Spec-defined future types
  STREAK_7: {
    id: 'STREAK_7',
    name: '7 Day Streak',
    icon: 'flame',
    iconColor: '#FF6B2B',
    description: 'Study every day for 7 days in a row.',
    criteria: '7 consecutive study days',
    category: 'streak',
  },
  STREAK_21: {
    id: 'STREAK_21',
    name: '21 Day Streak',
    icon: 'flame',
    iconColor: '#FF6B2B',
    description: 'Study every day for 21 days in a row.',
    criteria: '21 consecutive study days',
    category: 'streak',
  },
  HOURS_10: {
    id: 'HOURS_10',
    name: '10h Club',
    icon: 'time',
    iconColor: '#2D6BE4',
    description: 'Study a total of 10 hours across all subjects.',
    criteria: 'Accumulate 10 hours of study time',
    category: 'milestone',
  },
  HOURS_50: {
    id: 'HOURS_50',
    name: '50h Club',
    icon: 'star',
    iconColor: '#2D6BE4',
    description: 'Study a total of 50 hours.',
    criteria: 'Accumulate 50 hours of study time',
    category: 'milestone',
  },
  HOURS_100: {
    id: 'HOURS_100',
    name: '100h Club',
    icon: 'trophy',
    iconColor: '#FFD700',
    description: 'Study a total of 100 hours.',
    criteria: 'Accumulate 100 hours of study time',
    category: 'milestone',
  },
  NIGHT_OWL: {
    id: 'NIGHT_OWL',
    name: 'Night Owl',
    icon: 'moon',
    iconColor: '#8E44AD',
    description: 'Complete a session after midnight.',
    criteria: 'Study session ending after 12:00 AM',
    category: 'special',
  },
  EARLY_BIRD: {
    id: 'EARLY_BIRD',
    name: 'Early Bird',
    icon: 'sunny',
    iconColor: '#F39C12',
    description: 'Start a session before 6:00 AM.',
    criteria: 'Study session starting before 6 AM',
    category: 'special',
  },
  SESSIONS_10: {
    id: 'SESSIONS_10',
    name: 'Getting Started',
    icon: 'checkmark-circle',
    iconColor: '#27AE60',
    description: 'Complete 10 study sessions.',
    criteria: '10 total sessions completed',
    category: 'milestone',
  },
  GROUP_LEADER: {
    id: 'GROUP_LEADER',
    name: 'Group Leader',
    icon: 'people',
    iconColor: '#2D6BE4',
    description: 'Rank #1 in your study group for a full day.',
    criteria: 'Top of group leaderboard for one day',
    category: 'social',
  },

  // DB enum aliases — current backend AchievementType values
  FIRST_SESSION: {
    id: 'FIRST_SESSION',
    name: 'First Session',
    icon: 'checkmark-circle',
    iconColor: '#27AE60',
    description: 'Complete your very first study session.',
    criteria: '1 session completed',
    category: 'milestone',
  },
  STREAK_3: {
    id: 'STREAK_3',
    name: '3 Day Streak',
    icon: 'flame',
    iconColor: '#FF6B2B',
    description: 'Study every day for 3 days in a row.',
    criteria: '3 consecutive study days',
    category: 'streak',
  },
  TOTAL_1H: {
    id: 'TOTAL_1H',
    name: '1h Club',
    icon: 'time',
    iconColor: '#2D6BE4',
    description: 'Study a total of 1 hour.',
    criteria: 'Accumulate 1 hour of study time',
    category: 'milestone',
  },
  TOTAL_10H: {
    id: 'TOTAL_10H',
    name: '10h Club',
    icon: 'time',
    iconColor: '#2D6BE4',
    description: 'Study a total of 10 hours across all subjects.',
    criteria: 'Accumulate 10 hours of study time',
    category: 'milestone',
  },
  TOTAL_100H: {
    id: 'TOTAL_100H',
    name: '100h Club',
    icon: 'trophy',
    iconColor: '#FFD700',
    description: 'Study a total of 100 hours.',
    criteria: 'Accumulate 100 hours of study time',
    category: 'milestone',
  },
}

export const CATEGORY_LABELS = {
  streak: '🔥 Streak',
  milestone: '⏱ Milestone',
  special: '✨ Special',
  social: '👥 Social',
}
